### ISSUE TITLE
Bank tags tabs not reskinned

### ISSUE THREAD

**Issue by YannisGH** [melkypie/resource-packs#11]
Those bank tag tabs on the left side of your are not darkened with https://github.com/melkypie/resource-packs/tree/pack-osrs-dark , any chance this could be added? Love the reskin
![9309bb0c31a0e69f18029df366594f77](https://user-images.githubusercontent.com/47642097/83979842-88083980-a911-11ea-97b6-6d1531765967.png)

**Comment by melkypie** [comment]
Unfortunately this is not possible as the bank tags is a core runelite plugin and the plugin-hub plugins can't override what core plugins do.
