### ISSUE TITLE
Option to hide sidepanel button

### ISSUE THREAD

**Issue by m0bilebtw** [melkypie/resource-packs#117]
For those of us who find one pack they want to always use, it would be nice to be have a config option to hide the sidepanel button as we no longer need to open the sidepanel to browse packs. It would help de-clutter the ever growing list of icons. 

Other plugins can already dynamically hide their sidepanel button (zulrah plugin outside of zulandra, one of the party panel plugins if you're not in a party, etc), so tying it to a boolean config should be feasible!

**Comment by melkypie** [comment]
Closed by #120
