### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by JediLincoln** [melkypie/resource-packs#126]
Please turn off the theme-specific login screen, or at least provide an option to turn it off. I like to be able to see special login screen when they occur.

**Comment by CrossBowKill** [comment]
Just disable it in the Plugin settings 
![image](https://user-images.githubusercontent.com/19334778/151264150-d8130954-cd8e-421b-933b-3c5d076673e5.png)

**Comment by JediLincoln** [comment]
Thanks. Didn't know that was there.
