### ISSUE TITLE
Disable color current pack option by default

### ISSUE THREAD

**Issue by Netherland** [melkypie/resource-packs#129]
As title states.
After making my own custom resource pack and inserting it into the plugin, all the edited resources were overlaid with a red color making it appear like the resource pack was not working as intended.
It's rather confusing to have this option enabled by default.

**Comment by melkypie** [comment]
It is disabled by default https://github.com/melkypie/resource-packs/blob/master/src/main/java/melky/resourcepacks/ResourcePacksConfig.java#L138

**Comment by Netherland** [comment]
Oops, it seems like I have configured the plugin in the past and forgot about it. My bad!
