### ISSUE TITLE
Small graphical issue with the top corner "X" on "Bottom line" stone style.

### ISSUE THREAD

**Issue by SirBenvil** [melkypie/resource-packs#13]
The logout button in the top right corner, when playing resize-able and on the "Bottom line" stones style, got some small graphical issues. 

It gets stretched one pixel wider to the right, but what's more noticeable is on the left side of the cross, a strange small 2-3 pixel wide shadow gets added. 

It's very minor, but still an inconsistency, other than that I'm loving this interface style <3

The "X" on dark style:
![image](https://user-images.githubusercontent.com/39379389/84221542-c3ebfc00-aad5-11ea-8448-5440ce1fefbc.png)

The "X" on vanilla style:
![image](https://user-images.githubusercontent.com/39379389/84221557-d0705480-aad5-11ea-9811-f8c5d364ec4a.png)

**Comment by melkypie** [comment]
This is fixed in the latest sample vanilla pack, you will have to wait for other packs to update for them to fix it.
