### ISSUE TITLE
Combat Style :pummel: Is missing

### ISSUE THREAD

**Issue by wgh5** [melkypie/resource-packs#137]
I know there is a style called: **style_hammer_pummel.png** But this is a **different style** all together.
This style is (as far as I know) only used by the [Dinh's bulwark](https://oldschool.runescape.wiki/w/Dinh%27s_bulwark)

Reference: [Image of Missing Style](https://raw.githubusercontent.com/wgh5/Images/main/Issue.png)

I normally use the Dinh's Bulwark at these locations: [Bursting](https://oldschool.runescape.wiki/w/Ice_Barrage), [Wilderness](https://oldschool.runescape.wiki/w/Wilderness), [Chaos Temple](https://oldschool.runescape.wiki/w/Chaos_Temple_(hut)), boss tanking, tank gear, [Sarachnis](https://oldschool.runescape.wiki/w/Sarachnis)

Thank you for taking time to read this ❤️

**Comment by melkypie** [comment]
Added in 83a4ebfb662ee8f33645a5d9daad514be09f7abc
