### ISSUE TITLE
Hitpoint Orb Reverts When Poisoned

### ISSUE THREAD

**Issue by wgh5** [melkypie/resource-packs#139]
I have a **custom Hitpoint Orb Icon** [Reference](https://github.com/wgh5/Images/blob/main/hitpoint.PNG?raw=true)

When I am **[Venomed](https://oldschool.runescape.wiki/w/Venom), [Poisoned](https://oldschool.runescape.wiki/w/Poison), [Diseased](https://oldschool.runescape.wiki/w/Disease), [Parasite](https://oldschool.runescape.wiki/w/Parasite_(Phosani%27s_Nightmare))**, maybe some others... The hitpoint icon changes back to its original form and I would have to reload the pack to get it back.

Just wondering if there is anyway to fix this, if its not an easy fix for you then no need to worry its not that big of a deal.

Thanks for reading this ❤️

**Comment by melkypie** [comment]
This is not possible to do, as it is the Runelite Poison plugin that changes the icons and plugin hub plugins can't override core Runelite plugin behaviour. If you disable the Poison plugin there should not be any issues.
