### ISSUE TITLE
Will support be added for tag tabs in the near future?

### ISSUE THREAD

**Issue by TalHS** [melkypie/resource-packs#14]
<img width="724" alt="Screen Shot 2020-06-10 at 4 40 44 PM" src="https://user-images.githubusercontent.com/34493020/84321853-90db5400-ab39-11ea-9dbf-a5947abf0fee.png">

The new tab and tutorial buttons are also appear to be unchanged. This is a really cool plugin that I'd love to use, but the bank interface kinda looks awful rn.

**Comment by melkypie** [comment]
Support for bank tags cannot be added as I mentioned in #11. I will still leave this issue open as I need to add the tutorial and the new tab button

**Comment by melkypie** [comment]
Actually I was wrong and I found a solution to recolour the bank tag tabs and also the other stuff mentioned here. The plugin has been updated but the only pack that is currently updated for it is flatscape. I will close this as it is just the pack's maintainers choice to update it or not
