### ISSUE TITLE
[Resource pack] Hides non relevant prayers for doing PVM

### ISSUE THREAD

**Issue by EnkryptedOSRS** [melkypie/resource-packs#142]
Hides low level prayers, does not allow re-arranging ofcourse and the hidden ones can still be toggled on by clicking in their place
![hiddenprayers](https://user-images.githubusercontent.com/111094096/184252955-086878bc-e175-4907-8442-efc34ba18d20.PNG)

**Comment by EnkryptedOSRS** [comment]
Can't figure out how to make a branch to add the folders

**Comment by melkypie** [comment]
As there is currently a poll for specifically filtering which prayers in the prayer tab, I am closing this. Also there was a previous poll which did not pass, so technically currently this is still illegal.
