### ISSUE TITLE
unranked GIM tab icon

### ISSUE THREAD

**Issue by feelwood** [melkypie/resource-packs#147]
Is it possible to alter the unranked group ironman icon? I've downloaded the vanilla pack and the icon doesn't seem to be in there. Currently the icon is very out of place with my texture pack and I'm unable to find a way to change it. Currently there are icons for regular group ironman and hardcore but not unranked.

**Comment by melkypie** [comment]
Added in 83a4ebfb662ee8f33645a5d9daad514be09f7abc
