### ISSUE TITLE
[RL Immersive Pack] Fix Grand Exchange Offer Status

### ISSUE THREAD

**Issue by Jbleezy** [melkypie/resource-packs#149]
The bottom right of this screen is bugged.

**Comment by nickyGyul** [comment]
fixed as of v1.4.5

**Comment by Jbleezy** [comment]
It's still not fixed for me.

**Comment by nickyGyul** [comment]
The plugin was causing the issue, but now pack creators need to update the pack.

You'd need to join the discord and get the pack creator (BasVonSpace) to fix the pack and receive your other feedback.
