### ISSUE TITLE
Borders on GE slots not lining up

### ISSUE THREAD

**Issue by TalHS** [melkypie/resource-packs#17]
<img width="727" alt="Screen Shot 2020-06-15 at 1 42 08 PM" src="https://user-images.githubusercontent.com/34493020/84694135-50e7e880-af0e-11ea-8906-b98548750c0b.png">
It's fine when you first open the GE interface, but it seems to happen after collecting a completed offer.

**Comment by melkypie** [comment]
This will be fixed in next runelite release. Also you will have to redownload the pack after then for it to work properly.
