### ISSUE TITLE
Custom prayer tab icons are not working

### ISSUE THREAD

**Issue by Hacerio** [melkypie/resource-packs#185]
It appears that the game update on April 12th (which added the new prayer book in the beta worlds) has broken custom prayer tab icons. I don't know if the .png file just needs to be named something new besides "prayer.png", or if the plugin itself needs to be updated. Please advise.

**Comment by melkypie** [comment]
Interface styles has the same problem, once it is fixed there, it will be fixed in resource packs. Related to runelite/runelite#16486

**Comment by melkypie** [comment]
The fix has been merged into Runelite master and seems like was cherry-picked into 1.9.15. If the prayer icon is still not working, restarting the client should fix it.
