### ISSUE TITLE
I dont know what is causing this bug. It is happening with every resource pack. Help

### ISSUE THREAD

**Issue by Cosmic10** [melkypie/resource-packs#192]
![image](https://github.com/melkypie/resource-packs/assets/23667960/580e592e-4dc9-4217-899d-bae2415941bc)

**Comment by Hexoteric** [comment]
![image](https://github.com/melkypie/resource-packs/assets/123139321/08eb5e02-7df2-40e5-8de3-fe6b8ae7781b)

turn this off, should fix it. not a bug, you just messed with settings without realizing what youre messing with.
