### ISSUE TITLE
[CRAZED Resource Pack] Bank UI

### ISSUE THREAD

**Issue by IWORDI** [melkypie/resource-packs#198]
I want to start off by saying that I absolutely love this resource pack, but I have a very minor OCD related issue lol.. I was wondering if the overlapping of the buttons at the bottom of the bank tab windows could be fixed. Aside from that everything else is flawless!

**Comment by nickyGyul** [comment]
Most pack creators will be reachable in the #feedback channel in the [discord](https://discord.com/invite/DsDhUz4NNN). You can leave a screenshot with the Bank UI problem in there and hopefully they'll respond with a fix!

**Comment by IWORDI** [comment]
Oh okay, thank you so much! @nickyGyul
