### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by gc** [melkypie/resource-packs#20]
Hey, I like the plugin. Thank you for your work. I had a few suggestions that I think would be nice that I wanted to throw out there:

1. Ability to customize login-screen stuff (e.g. the login stone thing and the buttons on it)
2. Ability to add an overlay for fixed-mode. For example you know in streams how people sometimes have overlays or borders/frames around their stream? So its basically like a picture frame for this part of the screen: https://cdn.discordapp.com/attachments/357422607982919680/727482116710989875/unknown.png - so the overlay image that the resource pack would use, would be roughly the size of that image, for example you could fill the entire thing with black and you wouldnt be able to see anything ingame.
3. Would it be possible to have the login-screen background as part of a resource pack? So if we want to share a resource pack, we can have the login screen background bundled with it too. maybe you do the same as the login screen plugin does and just override whatever bg  is currently there?

**Comment by melkypie** [comment]
1. This is not currently possible with runelite
2. That's not really possible as the plugin can only replace sprites that are already there.
3. That is something that could be made, although I will probably have something like a config option to toggle this ability (default off) to not mess with people's own login screens.

**Comment by melkypie** [comment]
3. was added in acbaa25b8de89b0cc911f654e0ed5b51c9195f75
I will still leave this issue open if the login screen sprites can be customized in future.
