### ISSUE TITLE
Cross sprites sometimes don't load correctly

### ISSUE THREAD

**Issue by notadadyet** [melkypie/resource-packs#218]
For some reason it is random if the cross sprites load or not.  I am able to play everything else is changed, but the click sprites are still the regular runescape ones.  
Sorry I don't have more info but I can't get the sprites to be on whatever I do, restart client, flash plugin etc
thank you

**Comment by notadadyet** [comment]
Randomly no settings changed the sprites started working.

**Comment by raiyni** [comment]
Fixed in 5e8fd77463a9c17c163b4e1260238e2ace66a76a I believe
