### ISSUE TITLE
Reduce RL #support traffic - overlayBackgroundColor

### ISSUE THREAD

**Issue by YvesW** [melkypie/resource-packs#224]
We often get #support traffic because people change their ``overlay color`` in the ``RuneLite`` settings and then resource packs resets it later on. You have created a config option to disable this, but the users are not aware.

Could you please listen to changes of the RuneliteConfig in ConfigChanged and specifically for the ``overlayBackgroundColor`` key? If the value of this key is changed while ``allow overlay color to be changed`` is enabled, could you send a chat message in a red fontthat their resource pack will override the overlay color unless they disable ``allow overlay color to be changed`` in resource packs's config settings?
Alternatively, you could even disable ``allow overlay color to be changed`` via ConfigManager if the user changes ``overlayBackgroundColor``.

**Comment by raiyni** [comment]
added in https://github.com/melkypie/resource-packs/commit/f026016632c5b16cdb7907e2445c0453508787c4
