### ISSUE TITLE
Suggestion: Add inventory/ui icon support

### ISSUE THREAD

**Issue by GrimWrath** [melkypie/resource-packs#26]
I really would love to be able to use my 2010 inventory/prayer/equipment/ui etc icons with resource packs. Or maybe even make new ones. Can this be done? Not sure what the name of this set of icons is called.

**Comment by melkypie** [comment]
You can find the 2010 icons here https://github.com/runelite/runelite/tree/master/runelite-client/src/main/resources/net/runelite/client/plugins/interfacestyles/2010 . You will have to create your own pack with these icons as replacement for the vanilla ones..
