### ISSUE TITLE
117hd settings in screenshots

### ISSUE THREAD

**Issue by rabbitofdeth** [melkypie/resource-packs#276]
Hello can you please provide what 117hd settings you use in the screenshots for the 2010 hd overhaul pack? Your game looks so great and I want to copy those settings.. please and thank you.

**Comment by raiyni** [comment]
This isn't an issue for github, you can ask the author in game or discord.

**Comment by rabbitofdeth** [comment]
> This isn't an issue for github, you can ask the author in game or discord.

I understand, but do not know how to contact the author. Do you happen to have their discord?
