### ISSUE TITLE
Brown chat box and white line in bank.

### ISSUE THREAD

**Issue by Fixmypack** [melkypie/resource-packs#278]
![image](https://github.com/melkypie/resource-packs/assets/173741114/64a3f10c-129a-400c-9434-21cfc874e720)
 
My chat box in game has turned brown all of a sudden, instead of the flush white.  Along with in my bank tab there is a very annoying white line that goes across the top.  Can someone please fix this or tell me how to? is very irritating, after using and enjoying this pack for so long..

**Comment by Fixmypack** [comment]
![image](https://github.com/melkypie/resource-packs/assets/173741114/8934b42c-e62f-4d57-9e21-0952f4282ff2)
 there are also little lines now on my health and prayer bars too.. guys are killing me

**Comment by Fixmypack** [comment]
prayer is all messed up.. u changed all the icons for teleports and made my xp bar invis.. and that's all i can notice off the rip.. i could get over the dumb line in my bank but like why u guys gotta mess up this pack it was so good.. no one wanted u to touch it like this, ruined it for everyone.. its basically unplayable

**Comment by Fixmypack** [comment]
please help

**Comment by raiyni** [comment]
I suggest you contact the author with constructive feedback, being inflammatory towards volunteers isn't welcome here.
