### ISSUE TITLE
Suggestion - Dark Chatbox

### ISSUE THREAD

**Issue by mleves10** [melkypie/resource-packs#29]
Hi, have you guys considered making the chatbox dark mode as well?  In my opinion, having the beige default color doesn't mesh well with the dark mode inventory and other things.

Great resource pack though, appreciate it.

**Comment by melkypie** [comment]
The dark mode pack is made to be as similar to regular runescape as possible. Changing the chatbox dark would make the text pretty hard to read as there are some text colors that can't be changed by runelite. You can still however download the plugin, make the chatbox dark and use the old method to apply that resource pack. Also there is a Dark (Fixed) or Dark (Resizable) which both have dark chatboxes.
