### ISSUE TITLE
Add 2005 version resource pack

### ISSUE THREAD

**Issue by Pasato** [melkypie/resource-packs#47]
Hi all,

just want to say a huge thank you and want to say that i really appreciate the asthetic and it enhances the gameplay and fell, it doesn't go un-noticed.

One suggestion which would be incredible is similarly to th 2010 full remake, to make a 2005 version including the bank invy, item looks, textbox and camera.

Kind regards, 
big fan

**Comment by LeoFurnari** [comment]
Hi, I would like to add this sort of frame to this. I'm not sure how to create it though ![2005](https://user-images.githubusercontent.com/18450022/89370555-0897ac00-d6af-11ea-8400-c7c7bba4f14e.PNG)

**Comment by Pasato** [comment]
Yes, this would be excellent the post that LeoFurnari has suggested, exactly how i would have imagined it to have looked like. Would this perhaps be a possibility

:)

**Comment by LeoFurnari** [comment]
I tried downloading a resource pack to take a look, but there is no 2005 frame in the wiki to get a jumping off point from

**Comment by bpk908p** [comment]
I'd really like a 2005scape icon dark runelite as well!

**Comment by Septem151** [comment]
For those still interested in a 2005-esque resource pack, I've submitted a PR to get one onto the hub. #166
