### ISSUE TITLE
Graphical glitch with Skybox

### ISSUE THREAD

**Issue by Karambwanner** [melkypie/resource-packs#5]
Not a big issue, however if the skybox changes, the bottom right part of the minimap will change to the same color as the skybox. As an example, here's a picture of the bottom of the minimap while in my PoH. 
![image](https://user-images.githubusercontent.com/66223887/83363355-890ff880-a35e-11ea-8865-d029a79be929.png)

Now whenever I leave my PoH the bottom right section looks blue instead of black.
![image](https://user-images.githubusercontent.com/66223887/83363373-a0e77c80-a35e-11ea-948d-85d76aec3801.png)

This happens regardless of if the Skybox plugin is enabled, the only difference is the color. If the Skybox plugin is disabled it will turn a beige color.

**Comment by melkypie** [comment]
@iawhd the texture should be expanded a bit to account for that transparent space. I believe I have fixed this on the vanilla sample pack but I am not too sure.

**Comment by Karambwanner** [comment]
Yeah I believe the vanilla sample pack worked just fine, its only the dark theme pack that this is happening on. Again, not a big deal, but it does look a little annoying.

**Comment by iawhd** [comment]
@melkypie I've resolved this in the new 1.5 version
