### ISSUE TITLE
Too Dark :S

### ISSUE THREAD

**Issue by ghost** [melkypie/resource-packs#56]
This is EASILY the best skin on the entire plugin, but i was wondering it we could get the more darker pieces upped about 15% brightness, not much, and as a seperate version! this is a lovely theme, its just a bit hard on the eyes with the super dark contrast between the black and the red. If i could give any suggestion, it would be a slightly lighter version with blue instead of red, and I would totally do it if i knew how, but alas here i am asking for your assistance

**Comment by melkypie** [comment]
What pack exactly are you talking about? This repo contains all of the available packs not just one of them.

**Comment by Celestiul** [comment]
rip, i had 0 idea how github works. red&dark vanilla's chat is honestly terrible to read, and its the opposite for the "dark theme", which just blinds me with its chat. If i had annny idea how to change this stuff i would, but im not a coder
________________________________

**Comment by melkypie** [comment]
There is no need to be a coder as the packs are just image files (.png) that need to be changed. There is 0 coding involved in creating/changing a resource pack. Unfortunately I am pretty sure the original creator has abandoned the pack so your only hope is to edit it yourself or wait for someone else to come along

**Comment by Celestiul** [comment]
if you send, i can reedit myself if i can get a rundown of how to change
certain things, it would be nice

**Comment by melkypie** [comment]
The download for the pack is at https://github.com/melkypie/resource-packs/archive/pack-redblackvanilla.zip. Extract it and then look for the texture that you want to update. After you are done updating, to use the pack you should follow https://github.com/melkypie/resource-packs#old-method
