### ISSUE TITLE
vibrating tabs

### ISSUE THREAD

**Issue by jorbo** [melkypie/resource-packs#66]
In both the Reaper and Reaper Chroma resource packs the tabs in certain menus such as the quest menu and settings menu seem to vibrate back and forth ( See gif attached) This behavior doesn't happen with other packs such as Dragonframe.
![tab glitch](https://files.catbox.moe/gnjh0t.gif)

**Comment by EXpoZuR** [comment]
Currently not able to reproduce this. Please make sure the "interface styles" plugin is set to default whether it is on or off. Please try with GPU on and off in Runelite. Also change your stretched mode plugin settings to see if that fixes it.

**Comment by melkypie** [comment]
I am also unable to reproduce this. What is your Runelite, Launcher (both found in the info panel) and Resource packs version (found in the hub)?

**Comment by jorbo** [comment]
Runelite Version: 1.7.3
Launcher Version: 1.7.3
Resource Packs version: 1.3.1.1
and Im downloading them from the plugin hub.

I tried a bunch of different options with interface styles, scaling, and gpu plugins with no changes in behavior

**Comment by melkypie** [comment]
There is no launcher version 1.7.3. Also are you actually using Runelite and not some other 3rd party client based on Runelite?

**Comment by wikomatic** [comment]
I'd noticed this with numerous packs myself in OpenOSRS, I've been combining parts of packs to make a custom one for myself like some sort of UI gremlin, and I used to do tech support for a living. Hope this write up helps tracking down what's going on, or at least as a reference for what packs are effected.

***

I can reproduce in OpenOSRS. **I have not been able to reproduce in Runelite.**
![image](https://user-images.githubusercontent.com/21310646/113718157-5dfedf80-96ba-11eb-8253-64a3f40fa4a9.png)

Interface Styles set to default
![image](https://user-images.githubusercontent.com/21310646/113718216-6c4cfb80-96ba-11eb-875e-56ca2592582b.png)

GPU on
![image](https://user-images.githubusercontent.com/21310646/113718269-7a9b1780-96ba-11eb-8da2-771ab517250f.png)

Caught in screenshot behind the Q, A, and K. Jitter appears to happen every frame.
![image](https://user-images.githubusercontent.com/21310646/113718428-9d2d3080-96ba-11eb-9c78-da0916221bfa.png)

GPU off
![image](https://user-images.githubusercontent.com/21310646/113718492-b2a25a80-96ba-11eb-89cb-633889a8e9f3.png)

Issue persists, see behind M
![image](https://user-images.githubusercontent.com/21310646/113718588-ca79de80-96ba-11eb-8d9f-d795b4c8d77b.png)

***

Can confirm the issue occurs in many of the Hub packs under this setup. Names are from the Selected pack dropdown:
- **2012** ![image](https://user-images.githubusercontent.com/21310646/113719024-352b1a00-96bb-11eb-89fd-ad3f291abefd.png)
- **CRAZED** ![image](https://user-images.githubusercontent.com/21310646/113720937-162d8780-96bd-11eb-91d6-e918a6c67977.png)
- **Dark Theme** ![image](https://user-images.githubusercontent.com/21310646/113719132-4ecc6180-96bb-11eb-9952-4bb2720160dd.png)
- **Dark theme (Spacenation)** ![image](https://user-images.githubusercontent.com/21310646/113721195-4ecd6100-96bd-11eb-9819-5c4e55547cb4.png)
- **Default Nord** ![image](https://user-images.githubusercontent.com/21310646/113721021-29d8ee00-96bd-11eb-84a9-83ff6227d516.png)
- **Gray theme** ![image](https://user-images.githubusercontent.com/21310646/113720770-f8602280-96bc-11eb-9c65-4bcf13a10d3c.png)
- **Photophobia** ![image](https://user-images.githubusercontent.com/21310646/113719915-1d07ca80-96bc-11eb-8f45-debc2bdd8f31.png)
- **Pink Vanilla** ![image](https://user-images.githubusercontent.com/21310646/113720117-504a5980-96bc-11eb-9bf1-950cfc909402.png)
- **Purple Pack 1.3 V2**  ![image](https://user-images.githubusercontent.com/21310646/113718883-162c8800-96bb-11eb-9c5a-f801f65a30fa.png)
- **Reaper Chroma** ![image](https://user-images.githubusercontent.com/21310646/113720315-838ce880-96bc-11eb-9eac-0c3cf9652625.png) (As reported by @jorbo)
- **Reaper** ![image](https://user-images.githubusercontent.com/21310646/113721399-80462c80-96bd-11eb-861e-9736835e53e3.png) (As reported by @jorbo)
- **RedBlack&Vanilla** ![image](https://user-images.githubusercontent.com/21310646/113720537-bfc04900-96bc-11eb-9261-ed880701e012.png)
- **Twisted Theme** ![image](https://user-images.githubusercontent.com/21310646/113720597-d1a1ec00-96bc-11eb-8ebd-17eaaa39f099.png)

These packs are **not** effected:
- 2010 Legacy
- Dark (fixed)
- Dark (resizeable)
- Dark Side of Gilenor
- Dragonframe
- Flatscape
- High Detail
- Orange
- PrincessLite
- psyda Midnight
- Sand Casino
- Wood cabin (Resizeable)

***

So... guessing we're SOL and this should be reported to OpenOSRS, seeing as it doesn't happen in Runelite? That's weird as hell though, I wouldn't _expect_ any significant changes with the handling of UI textures between the two.

**Comment by melkypie** [comment]
The plugin is meant only for Runelite and I won't be providing support for clients that are clearly not allowed by Jagex.
