### ISSUE TITLE
Resizeable Tab Transparency

### ISSUE THREAD

**Issue by runeliteuser25** [melkypie/resource-packs#67]
Currently the side-panel tab seems to not read transparency, as in:

Transparency Off results in a fully non-transparent image (unless the background image has 0% opacity)

Transparency On results in x% opacity, regardless of image opacity.

Could this be changed to allow for custom opacity of the side-panel tab?

**Comment by melkypie** [comment]
Can you provide a screenshot?
I have no idea what transparency option you are talking about.

**Comment by MiniMe1025** [comment]
I am having this issue also id love to see a solution on my game (i use resizable mode) i made my own pack so I could add an image behind my inventory and I've also found there is only 2 options that work when making an image. Either the image is 100% transparent or it is not. I am trying to make a image show up that has a fully transparent background and a semi transparent image.
These files are an example of what I'm trying to achieve. File flag 1 is a image with a transparent background and the flag is not transparent. In the other file flag 2 the background is transparent and the flag is only partially transparent and this is what i am trying to achive in game. however when i use either file it will show in game that the flag has no transparency.
Please help.
![flag 1](https://user-images.githubusercontent.com/82183552/114101725-22b80880-9894-11eb-8c9f-4678bd31901c.png)
![flag 2](https://user-images.githubusercontent.com/82183552/114101729-251a6280-9894-11eb-8ebd-51d0a6157c11.png)

**Comment by melkypie** [comment]
OSRS can't use transparency in it's sprites, so it isn't possible to do.
