### ISSUE TITLE
Resource packs resets overlay color when the plugin/client is restarted.

### ISSUE THREAD

**Issue by geheur** [melkypie/resource-packs#80]
1. Change the overlay color in "Runelite" config.
2. Shutdown "Resource packs".
3. Startup "Resource packs". This will change the overlay color back to the original value it had before step 1. This doesn't seem right.

**Comment by melkypie** [comment]
This is the correct behaviour. You most likely are using a pack that overrides the overlay color. So changing the overlay color in Runelite settings and then restarting the plugin will override the one you set with the pack's defined one.
If you don't want this behaviour you can uncheck `Allow overlay color to be changed` in config

**Comment by geheur** [comment]
Ah. I didn't expect it to work that way since the color change works until
you either restart the client or the plugin, so it looks like a bug. Made
this issue because someone in#support was asking why their overlay color
reset when they restarted their client.
