### ISSUE TITLE
Combat Style Buttons - unused assets?

### ISSUE THREAD

**Issue by runeliteuser25** [melkypie/resource-packs#81]
Hi.

It seems the combat style assets are not actually in use - but instead use the edge_(location) and middle(_selected) assets.

These are shared with other functions (I noticed some of the bank buttons use these, and I'm sure there are more).

Not sure whether this is intentional, or if it can be fixed if it isn't - but it'd be nice for these two to not be interconnected :)

**Comment by melkypie** [comment]
Usually it is hard to see if something is actually unused as it might be used in some obscure interface that is old so I refrain from removing sprites if they are still in the OSRS cache. 
The plugin uses Runelite's SpriteOverride which can override specific sprites and does not allow to selectively replace sprites based on where they are displayed, so this is not possible.
