### ISSUE TITLE
Add support for the quest journal/quest completion background

### ISSUE THREAD

**Issue by TheDeviantCrafter** [melkypie/resource-packs#85]
Specifically the scroll-shaped background in this image: ![image](https://user-images.githubusercontent.com/18755309/120586377-0d291000-c3f9-11eb-9255-6d40cbbb5c34.png)

I was unable to find the image in the simple vanilla resource pack. None of the resource packs I've tested so far modified the screen.

**Comment by melkypie** [comment]
It is not possible with current RL api, as that is a model not a sprite.
