### ISSUE TITLE
[iawhd's Dark theme] Adding relic_unlock_locked sprite to the emote folder of the resource pack

### ISSUE THREAD

**Issue by nickyGyul** [melkypie/resource-packs#95]
The Relic unlock emote locked sprite is not included in iawhd's "Dark theme" resource pack. 

Right now the pack from the hub looks like [this](https://i.imgur.com/1pVamZc.png). The new emote looks brown instead of [black](https://i.imgur.com/KTtrusZ.png). If the following sprite could be added to the emote folder of the pack, it'll be greatly appreciated. Thanks in advance!

relic_unlock_locked
![relic_unlock_locked](https://user-images.githubusercontent.com/72536899/125526373-a43f8f8b-9cc0-453f-92e9-f5f39e5a67cf.png)

**Comment by melkypie** [comment]
@iawhd
