### ISSUE TITLE
Reaper Theme Quest Button

### ISSUE THREAD

**Issue by ZurielRedux** [melkypie/resource-packs#96]
The new "Character Summary" Doesnt have an Icon and since it is the default option it sort of breaks the aesthetic. Can this be updated with maybe a "C"? not sure if the original developer is still updating this, but if not, the "M" that was for minigames could probably be substituted as Main or something?

**Comment by melkypie** [comment]
@expozur

**Comment by EXpoZuR** [comment]
Will look into updating soon.

**Comment by melkypie** [comment]
This has been added in 6679c8426e9c48face2f0af6f9acb015297e42a6
